-- MySQL Script generated by MySQL Workbench
-- Fri 12 Jan 2018 07:49:35 PM EAT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema bulkpay
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bulkpay
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bulkpay` DEFAULT CHARACTER SET utf8 ;
USE `bulkpay` ;

-- -----------------------------------------------------
-- Table `bulkpay`.`tbl_permission`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bulkpay`.`tbl_permission` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NULL,
  `description` VARCHAR(100) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bulkpay`.`tbl_role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bulkpay`.`tbl_role` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NULL,
  `description` VARCHAR(100) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bulkpay`.`tbl_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bulkpay`.`tbl_user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(50) NULL,
  `password` VARCHAR(100) NULL,
  `email` VARCHAR(100) NULL,
  `full_name` VARCHAR(100) NULL,
  `role_id` INT NOT NULL,
  `enabled` TINYINT(1) NULL DEFAULT 0,
  PRIMARY KEY (`id`, `role_id`),
  UNIQUE INDEX `unique_user` (`username` ASC),
  INDEX `fk_tbl_user_tbl_role1_idx` (`role_id` ASC),
  CONSTRAINT `fk_tbl_user_tbl_role1`
    FOREIGN KEY (`role_id`)
    REFERENCES `bulkpay`.`tbl_role` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bulkpay`.`tbl_role_permission`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bulkpay`.`tbl_role_permission` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `permission_id` INT NOT NULL,
  `role_id` INT NOT NULL,
  `status` TINYINT(1) NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  INDEX `fk_tbl_role_permission_tbl_permission_idx` (`permission_id` ASC),
  INDEX `fk_tbl_role_permission_tbl_role1_idx` (`role_id` ASC),
  CONSTRAINT `fk_tbl_role_permission_tbl_permission`
    FOREIGN KEY (`permission_id`)
    REFERENCES `bulkpay`.`tbl_permission` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_role_permission_tbl_role1`
    FOREIGN KEY (`role_id`)
    REFERENCES `bulkpay`.`tbl_role` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bulkpay`.`tbl_company`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bulkpay`.`tbl_company` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NULL,
  `msisdn` VARCHAR(20) NULL,
  `pin` VARCHAR(10) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bulkpay`.`tbl_company_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bulkpay`.`tbl_company_user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `company_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `level` INT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  INDEX `fk_tbl_company_user_tbl_company1_idx` (`company_id` ASC),
  INDEX `fk_tbl_company_user_tbl_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_tbl_company_user_tbl_company1`
    FOREIGN KEY (`company_id`)
    REFERENCES `bulkpay`.`tbl_company` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_company_user_tbl_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `bulkpay`.`tbl_user` (`role_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bulkpay`.`tbl_batch`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bulkpay`.`tbl_batch` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `method` VARCHAR(20) NULL DEFAULT 'FILE',
  `records` BIGINT NULL DEFAULT 0,
  `amount` DOUBLE NULL DEFAULT 0.00,
  `status` TINYINT(4) NULL DEFAULT 0,
  `level` TINYINT(4) NULL DEFAULT 0,
  `name` VARCHAR(100) NULL,
  `payer` INT NOT NULL,
  `initiated_by` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tbl_batch_tbl_company1_idx` (`payer` ASC),
  INDEX `fk_tbl_batch_tbl_company_user1_idx` (`initiated_by` ASC),
  CONSTRAINT `fk_tbl_batch_tbl_company1`
    FOREIGN KEY (`payer`)
    REFERENCES `bulkpay`.`tbl_company` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_batch_tbl_company_user1`
    FOREIGN KEY (`initiated_by`)
    REFERENCES `bulkpay`.`tbl_company_user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bulkpay`.`tbl_payment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bulkpay`.`tbl_payment` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `trans_id` VARCHAR(50) NULL,
  `amount` DOUBLE NULL,
  `msisdn` VARCHAR(45) NULL,
  `status` INT NULL DEFAULT 0,
  `message` VARCHAR(45) NULL,
  `batch_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tbl_payment_tbl_batch1_idx` (`batch_id` ASC),
  CONSTRAINT `fk_tbl_payment_tbl_batch1`
    FOREIGN KEY (`batch_id`)
    REFERENCES `bulkpay`.`tbl_batch` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bulkpay`.`tbl_audit`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bulkpay`.`tbl_audit` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `task` VARCHAR(45) NULL,
  `user_id` INT NOT NULL,
  `role_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tbl_audit_tbl_user1_idx` (`user_id` ASC),
  INDEX `fk_tbl_audit_tbl_role1_idx` (`role_id` ASC),
  CONSTRAINT `fk_tbl_audit_tbl_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `bulkpay`.`tbl_user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_audit_tbl_role1`
    FOREIGN KEY (`role_id`)
    REFERENCES `bulkpay`.`tbl_role` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
